<?php
/*
 * NSA/DHS "News Feed" generator for the TrackMeNot browser plugin.
 * <https://github.com/parseword/util-misc/nsa-dhs-news.php>
 * This script is in the public domain.
 *
 * NSA TAO cryptonym wordlist from:
 * <https://electrospaces.blogspot.com/p/nsas-tao-division-codewords.html>
 *
 * Department of Homeland Security social media monitoring wordlist from:
 * <http://www.forbes.com/sites/reuvencohen/2012/05/26/department-of-homeland-security-forced-to-release-list-of-keywords-used-to-monitor-social-networking-sites/2/>
 */

$keywords = array(
    //DHS watchlist
    '2600',
    'Abu Sayyaf',
    'Afghanistan',
    'Agriculture',
    'Agro',
    'Agro Terror',
    'Aid',
    'Airplane',
    'Airport',
    'Al Qaeda',
    'Al-Shabaab',
    'Ammonium nitrate',
    'AMTRAK',
    'Anthrax',
    'Antiviral',
    'AQAP',
    'AL Qaeda Arabian Peninsula',
    'AQIM',
    'Al Qaeda in the Islamic Maghreb',
    'Arellano-Felix',
    'Artistic Assassins',
    'Assassination',
    'Attack',
    'Avalanche',
    'Avian',
    'Bacteria',
    'Barrio Azteca',
    'BART',
    'Basque Separatists',
    'Beltran-Leyva',
    'Biological',
    'Biological infection',
    'Biological weapon',
    'Black out',
    'Blister agent',
    'Blizzard',
    'Body scanner',
    'Bomb squad',
    'Bomb threat',
    'Border',
    'Botnet',
    'Breach',
    'Bridge',
    'Brown out',
    'Brush fire',
    'Brute forcing',
    'Burn',
    'Burst',
    'Bust',
    'Cain and abel',
    'Calderon',
    'Cancelled',
    'Car bomb',
    'Cartel',
    'Cartel de Golfo',
    'Center for Disease Control',
    'CDC',
    'Chemical',
    'Chemical agent',
    'Chemical burn',
    'Chemical fire',
    'Chemical spill',
    'Chemical weapon',
    'China',
    'CIKR',
    'Ciudad Juarez',
    'Closure',
    'Cloud',
    'Cocaine',
    'Collapse',
    'Colombia',
    'Communications',
    'Computer infrastructure',
    'Conficker',
    'Consular',
    'Contamination',
    'Conventional weapon',
    'Cops',
    'Crash',
    'Crest',
    'Critical infrastructure',
    'Cyber attack',
    'Cyber Command',
    'Cyber security',
    'Cyber terror',
    'DDOS',
    'Deaths',
    'Decapitated',
    'Delays',
    'Denial of service',
    'Dirty bomb',
    'Disaster assistance',
    'Disaster management',
    'Disaster medical assistance team',
    'DMAT',
    'Disaster',
    'DNDO',
    'Domestic Nuclear Detection Office',
    'Dock',
    'Domestic nuclear detection',
    'Domestic security',
    'Drill',
    'Drug',
    'Drug Administration',
    'Drug cartel',
    'Drug trade',
    'Drug war',
    'E. Coli',
    'Earthquake',
    'Ebola',
    'Eco terrorism',
    'El Paso',
    'Electric',
    'Emergency',
    'Emergency Broadcast System',
    'Emergency Landing',
    'Emergency management',
    'Emergency response',
    'Enriched',
    'Environmental terrorist',
    'Epidemic',
    'Erosion',
    'ETA',
    'Euskadi ta Askatasuna',
    'Evacuation',
    'Execution',
    'Exercise',
    'Explosion',
    'explosive',
    'Exposure',
    'Extreme weather',
    'Extremism',
    'Facility',
    'Failure or outage',
    'FARC',
    'First responder',
    'Flood',
    'Flu',
    'Food Poisoning',
    'Foot and Mouth',
    'FMD',
    'Forest fire',
    'Fort Hancock',
    'Fundamentalism',
    'Gang',
    'Gangs',
    'Gas',
    'Grid',
    'Gulf Cartel',
    'Gunfight',
    'Guzman',
    'H1N1',
    'H5N1',
    'Hacker',
    'Hail',
    'Hamas',
    'Hazardous',
    'Hazardous material incident',
    'Hazmat',
    'Help',
    'Heroin',
    'Hezbollah',
    'Home grown',
    'Homeland security',
    'Hostage',
    'Human to Animal',
    'Human to human',
    'Hurricane',
    'Ice',
    'IED',
    'Illegal immigrants',
    'Improvised explosive device',
    'Incident',
    'Industrial spill',
    'Infection',
    'Influenza',
    'infrastructure',
    'Infrastructure security',
    'Interstate',
    'IRA',
    'Irish Republican Army',
    'Iran',
    'Iraq',
    'Islamist',
    'Jihad',
    'Juarez',
    'Keylogger',
    'Kidnap',
    'La Familia',
    'Law enforcement Authorities',
    'Leak',
    'Lightening',
    'Listeria',
    'Lockdown',
    'Looting',
    'Los Zetas',
    'MAGIC MERV',
    'Magnitude',
    'Malware',
    'Mara salvatrucha',
    'Marijuana',
    'Maritime domain awareness',
    'MDA',
    'MARTA',
    'Matamoros',
    'Meth Lab',
    'Methamphetamine',
    'Metro',
    'Mexican army',
    'Mexicles',
    'Mexico',
    'Michoacana',
    'Militia',
    'Mitigation',
    'MS13',
    'MS-13',
    'Mud slide',
    'Mudslide',
    'Mutation',
    'Mysql injection',
    'Narco banners',
    'Narcos',
    'Narcotics',
    'National infrastructure',
    'National laboratory',
    'National preparedness',
    'National preparedness initiative',
    'National security',
    'Nationalist',
    'NBIC',
    'National Biosurveillance Integration Center',
    'Nerve agent',
    'New Federation',
    'Nigeria',
    'Nogales',
    'North Korea',
    'Norvo Virus',
    'Nuclear facility',
    'Nuclear threat',
    'Nuclear',
    'Nuevo Leon',
    'Organized crime',
    'Outbreak',
    'Pakistan',
    'Pandemic',
    'Phishing',
    'Phreaking',
    'Pipe bomb',
    'Pirates',
    'Plague',
    'PLF',
    'Palestine Liberation Front',
    'PLO',
    'Palestine Liberation Organization',
    'Plot',
    'Plume',
    'Police',
    'Pork',
    'Port',
    'Port Authority',
    'Powder (white)',
    'Power lines',
    'Power outage',
    'Power',
    'Prevention',
    'Public Health',
    'Quarantine',
    'Radiation',
    'Radicals',
    'Radioactive',
    'Recall',
    'Recovery',
    'Recruitment',
    'Relief',
    'Resistant',
    'Response',
    'Reynosa',
    'Reyosa',
    'Ricin',
    'Riot',
    'Rootkit',
    'Salmonella',
    'San Diego',
    'Sarin',
    'Scammers',
    'Screening',
    'Security',
    'Service disruption',
    'Shelter-in-place',
    'Shooting',
    'Shootout',
    'Shots fired',
    'Sick',
    'Sinaloa',
    'Sleet',
    'Small Pox',
    'Smart',
    'Smuggling (smugglers)',
    'Snow',
    'Social media',
    'Somalia',
    'Sonora',
    'Southwest',
    'Spammer',
    'Spillover',
    'Standoff',
    'State of emergency',
    'Storm',
    'Strain',
    'Stranded/Stuck',
    'Subway',
    'Suicide attack',
    'Suicide bomber',
    'Suspicious package',
    'Suspicious substance',
    'SWAT',
    'Swine',
    'Symptoms',
    'Taliban',
    'Tamaulipas',
    'Tamiflu',
    'Tamil Tigers',
    'Target',
    'Telecommunications',
    'Temblor',
    'Terrorism',
    'Terror',
    'Threat',
    'Tijuana',
    'Tornado',
    'Torreon',
    'Toxic',
    'Trafficking',
    'Transportation security',
    'Tremor',
    'Trojan',
    'Tsunami',
    'Tsunami Warning Center',
    'TTP',
    'Tehrik-i-Taliban Pakistan',
    'Tuberculosis (TB)',
    'Tucson',
    'Twister',
    'Typhoon',
    'U.S. Consulate',
    'Vaccine',
    'Violence',
    'Viral Hemorrhagic Fever',
    'Virus',
    'Warning',
    'Watch',
    'Water/air borne',
    'Wave',
    'Weapons cache',
    'Weapons grade',
    'Wildfire',
    'WMATA',
    'World Health Organization',
    'WHO',
    'Worm',
    'Yemen',
    'Yuma',
    //NSA TAO cryptonyms
    'ACRIDMINI',
    'ADJUTANT VENTURE',
    'ALOOFNESS',
    'ALTEREDCARBON',
    'AMULETSTELLAR',
    'ANGRYNEIGHBOR',
    'APERTURESCIENCE',
    'ARGYLEALIEN',
    'ARKSTREAM',
    'ARROWECLIPSE',
    'BADDECISION',
    'BALLOONKNOT',
    'BANANAAID',
    'BANANABALLOT',
    'BANNANADAIQUIRI',
    'BANANAGLEE',
    'BANANALIAR',
    'BARGLEE',
    'BARICE',
    'BARNFIRE',
    'BARPUNCH',
    'BEACHHEAD',
    'BEECHPONY',
    'BEIGETHICKET',
    'BENIGNCERTAIN',
    'BERSERKR',
    'BILLOCEAN',
    'BISHOP KNIGHT',
    'BLACK ENERGY Bot',
    'BLATSTING',
    'BLINDDATE',
    'BLIND MARKSMAN',
    'BLUISHDEFER',
    'BOOKISHMUTE',
    'BORGERKING',
    'BOTANICREALTY',
    'BOXINGRUMBLE',
    'BRICKTOP',
    'BROKENTIGO',
    'BULLDOZER',
    'BUZZDIRECTION',
    'BYZANTINE',
    'BYZANTINE ANCHOR',
    'BYZANTINE CANDOR',
    'BYZANTINE FOOTHOLD',
    'BYZANTINE HADES',
    'BYZANTINE PRAIRIE',
    'BYZANTINE RAPTOR',
    'BYZANTINE TRACE',
    'BYZANTINE VIKING',
    'CAPTIVATEDAUDIENCE',
    'CARBON PEPTIDE',
    'CASTLECRASHER',
    'CASTLECREEK',
    'CATFLAP',
    'CENTRICDUD',
    'CHAOSOVERLORD',
    'CHARMS',
    'CHELSEABLUE',
    'CHIMNEYPOOL',
    'CHOCOLATESHIP',
    'CHOCOPOP',
    'CLIMBINGSHIRT',
    'CLOUDSHIELD',
    'CLUCKLINE',
    'COLOSSUS',
    'COMMON',
    'COMMONDEER',
    'CONFICKER',
    'CONJECTURE',
    'CONTAINMENTGRID',
    'COTTONMOUTH',
    'COTTONMOUTH-I',
    'COTTONMOUTH-II',
    'COTTONMOUTH-III',
    'CROSSBEAM',
    'CROSSBONES',
    'CROSSEYEDSLOTH',
    'CROWNPRINCE',
    'CROWNROYAL',
    'CRYPTICSENTINEL',
    'CURSES',
    'CUTEBOY',
    'CYBERCOP',
    'CYBERQUEST',
    'DAMPCROWD',
    'DANCING PANDA',
    'DANDERSPRITZ',
    'DAREDEVIL',
    'DARKFIRE',
    'DARKHELMET',
    'DARKTHUNDER',
    'DAYTONSUNDAY',
    'DEAD SEA',
    'DEEPFRIEDPIG',
    'DEFIANTWARRIOR',
    'DEITYBOUNCE',
    'DEMENTIAWHEEL',
    'DESERTWINTER',
    'DEWDROP',
    'DEWSWEEPER',
    'DIESEL RATTLE',
    'DIRESCALLOP',
    'DISABLEVALOR',
    'DISCOROUTE',
    'DISCOVERY',
    'DOCKETDICTATE',
    'DOGROUND',
    'DOUBLEPULSAR',
    'DOURMAGNUM',
    'DRINKPARSLEY',
    'DROPMIRE',
    'DROPOUTJEEP',
    'DUBMOAT',
    'DURABLENAPKIN',
    'EARLYSHOVEL',
    'EASYKRAKEN',
    'EBB',
    'EBBISLAND',
    'ECLECTICPILOT',
    'EGGBASKET',
    'EGOTISTICALGIRAFFE',
    'EGOTISTICALGOAT',
    'EGREGIOUSBLUNDER',
    'ELATEDMONKEY',
    'ELDESTMYRIAD',
    'ELECTRICSLIDE',
    'ELEGANTEAGLE',
    'ELEONORE',
    'ELGINGAMBLE',
    'ELIGIBLEBACHELOR',
    'ELIGIBLEBOMBSHELL',
    'ELIGIBLECANDIDATE',
    'ELIGIBLECONTESTANT',
    'ENDLESSDONUT',
    'ENEMYRUN',
    'ENGLANDBOGGY',
    'ENVISIONCOLLISION',
    'ENVOYTOMATO',
    'EPICBANANA',
    'EPICHERO',
    'EQUATION Group',
    'ERRONEOUSINGENUITY',
    'ESCALATEPLOWMAN',
    'ESTOPMOONLIT',
    'ETERNALBLUE',
    'ETERNALCHAMPION',
    'ETERNALROMANCE',
    'ETERNALSYNERGY',
    'EVOLVINGSTRATEGY',
    'EWOK',
    'EWORKFRENZY',
    'EXACTCHANGE',
    'EXPLODINGCAN',
    'EXPOXYRASIN',
    'EXTRABACON',
    'EXTREMEPARR',
    'EXZE',
    'FABULOUSFABLE',
    'FAKEDOUBT',
    'FALSEMOREL',
    'FANNER',
    'FASHIONCLEFT',
    'FEEDTROUGH',
    'FELONYCROWBAR',
    'FERRETCANON',
    'FESTIVEWRAPPER',
    'FIGBUILD',
    'FINKCOAT',
    'FINKDIFFERENT',
    'FIREWALK',
    'FLASHHANDLE',
    'FLATLIQUID',
    'FLAXENPRECEPT',
    'FLEWAVENUE',
    'FLOCKFORWARD',
    'FLUXBABBITT',
    'FOGGYBOTTOM',
    'FOGGYBOTTOM2',
    'FOGYNULL',
    'FORKPTY',
    'FORRESTPLACE',
    'FOSHO',
    'FOXACID',
    'FOXSEARCH',
    'FREEFLOW',
    'FREEZEPOST',
    'FROZENGAZE',
    'FRUGALSHOT',
    'FUNNELAPS',
    'FUZZBUNCH',
    'GADGET HISS',
    'GECKO II',
    'GENESIS',
    'GENIE',
    'GHOST',
    'GHOSTRECON',
    'GNOMEFISHER',
    'GNOMEVISION',
    'GODSURGE',
    'GOLLUM',
    'GOPHERRAGE',
    'GOPHERSET',
    'GOSSIPGIRL',
    'GOTHAM',
    'GOTHAMKNIGHT',
    'GOURMETTROUGH',
    'GROK',
    'GUMFISH',
    'HALLUXWATER',
    'HAMMERCHANT',
    'HAMMERMILL',
    'HAMMERSTEIN',
    'HANGARSURPLUS',
    'HAPPYFOOT',
    'HAPPYHOUR',
    'HAWALA',
    'HEADMOVIES',
    'HEADWATER',
    'HEAVENSLEW',
    'HIDDENTEMPLE',
    'HIGHLANDS',
    'HOGTECH',
    'HOWLERMONKEY',
    'HUFF',
    'HYDROCASTLE',
    'ICYTWINS',
    'INCAADAM',
    'INCISION',
    'INFOSPYDER',
    'INTOLERANT',
    'IRATEMONK',
    'IRONAVENGER',
    'IRONCHEF',
    'IRONPERSISTANCE',
    'ITIME',
    'JACKLADDER',
    'JEEPFLEA',
    'JEEPFLEA_MARKET',
    'JEEPFLEA_POWDER',
    'JETPLOW',
    'JIFFYRAUL',
    'JOLLYROGER',
    'JUMPDOLLAR',
    'JUNIORMINT',
    'JUSTVISITING',
    'KILLSUIT',
    'KIRKBOMB',
    'KOALAPUNCH',
    'KONGUR',
    'KRISPYKREME',
    'LEAKYFAUCET',
    'LEGION AMBER',
    'LEGION AMETHYST',
    'LEGION JADE',
    'LEGION RUBY',
    'LEGION YANKEE',
    'LIFESAVER',
    'LOUDAUTO',
    'LUTEUSICARUS',
    'LUTEUSOBSTOS',
    'MADBISHOP',
    'MAESTRO-II',
    'MAGICBEAN',
    'MAGICJACK',
    'MAGICSQUIRREL',
    'MAGNETIC',
    'MAGNUMOPUS',
    'MAKERSMARK',
    'MAVERICK CHURCH',
    'MIDDLEMAN',
    'MINERALIZE',
    'MIRROR',
    'MISTYVEAL',
    'MOCCASIN',
    'MONKEYCALENDAR',
    'MOUSETRAP',
    'MURPHYSLAW',
    'NATIVE DANCER',
    'NEBULA',
    'NETSPYDER',
    'NIGHTWATCH',
    'NIGHTSTAND',
    'NIGHTTRAIN',
    'NITESTAND',
    'NITRO ZEUS',
    'NOPEN',
    'ODDJOB',
    'OLYMPIC',
    'OLYMPIC GAMES',
    'OLYMPUS',
    'OPTICPINCH',
    'ORANGUTAN',
    'ORLEANSTRIDE',
    'PACKETWRENCH',
    'PANDAROCK',
    'PANDORAS MAYHEM',
    'PARCHDUSK',
    'PASSIONATEPOLKA',
    'PASTEPIG',
    'PATCHICILLIN',
    'PCLEAN',
    'PEDDLECHEAP',
    'PERFECT CITIZEN',
    'PHOENIX Exploit Kit',
    'PHOTOANGLO',
    'PITIEDFOOL',
    'PLAIDDIANA',
    'PLUCKHAGEN',
    'POLARBREEZE',
    'POLARPAWS',
    'POLARSNEEZE',
    'POLARSTARKEY',
    'POLITERAIN',
    'POPROCKS',
    'POPQUIZ',
    'PORK',
    'POTBED',
    'PROTOSS',
    'PUZZLECUBE',
    'QFIRE',
    'QUANTUM',
    'QUANTUMBISCUIT',
    'QUANTUMBOT',
    'QUANTUMBOT2',
    'QUANTUMCOOKIE',
    'QUANTUMCOPPER',
    'QUANTUMDIRK',
    'QUANTUMDNS',
    'QUANTUMHAND',
    'QUANTUMINSERT',
    'QUANTUMMUSH',
    'QUANTUMNATION',
    'QUANTUMPHANTOM',
    'QUANTUMSKY',
    'QUANTUMSMACKDOWN',
    'QUANTUMSPIN',
    'QUANTUMSQUEEL',
    'QUANTUMSQUIRREL',
    'QUANTUMTHEORY',
    'QWERTY',
    'RADON',
    'RAGEMASTER',
    'RAISEBED',
    'RAPTOR JOY',
    'RAPTOR ROLEX',
    'RAPORT SAD',
    'RATWHARF',
    'RECORDER',
    'REGIN',
    'REPLICANTFARM',
    'RETICULUM',
    'RETURNSPRING',
    'REXKWONDO',
    'ROGUESAMURAI',
    'ROOTKNOT',
    'SADDLEBACK',
    'SALVAGERABBIT',
    'SCHOOLMONTANA',
    'SCREAMINGHARPY',
    'SCREAMINGPLOW',
    'SEAGULLFARO',
    'SEASONEDMOTH',
    'SECONDDATE',
    'SEED SPHERE',
    'SENTRY EAGLE',
    'SENTRY HAWK',
    'SENTRY FALCON',
    'SERUM',
    'SHADOWDRAGON',
    'SHAREDTAFFY',
    'SHARPFOCUS',
    'SHARPSHADOW',
    'SHELLGREY',
    'SHENTYSDELIGHT',
    'SHEPARD',
    'SHORTSHEET',
    'SHOTGIANT',
    'SHOUTPIG',
    'SIDETRACK',
    'SIERRAMONTANA',
    'SIFT',
    'SILLYBUNNY',
    'SKIMCOUNTRY',
    'SKYHOOKCHOW',
    'SLICKERVICAR',
    'SLIPSTREAM',
    'SLYHERETIC_CHECKER',
    'SNORT',
    'SNOWGLOBE',
    'SODAPRESSED',
    'SOLARTIME',
    'SOMBERKNAVE',
    'SOUFFLETROUGH',
    'SPARROW II',
    'SPECULATION',
    'SPINALTAP',
    'SPITEFULANGEL',
    'SQUASHCHUNKY',
    'STEALTHFIGTHER',
    'STEELFLAUTA',
    'STOICSURGEON',
    'STORMPIG',
    'STOWAGEWINK',
    'STRAITACID',
    'STRAIGHTBIZARRE',
    'STRAITSHOOTER',
    'STRIFEWORLD',
    'STRIKEZONE',
    'STRONGMITE',
    'STUCCOMONTANA',
    'STUMPCURSOR',
    'STUXNET',
    'STYLISHCHAMP',
    'SUAVEEYEFUL',
    'SUBTLESNOW',
    'SUCTIONCHAR',
    'SULPHURWRITE',
    'SUPERDRAKE',
    'SURLEYSPAWN',
    'SURPASSPIN',
    'SURPLUSHANGAR',
    'SUTURESAILOR',
    'SWAP',
    'TEFLONDOOR',
    'THERMALDIFFUSION',
    'TITAN RAIN',
    'TOAST',
    'TORNSTEAK',
    'TOTECHASER',
    'TOTEGHOSTLY',
    'TRANSGRESSION',
    'TREACLEBETA',
    'TRINITY',
    'TUNINGFORK',
    'TURBINE',
    'TURBOPANDA',
    'TUTELAGE',
    'TWEEZERS',
    'TWISTEDKILT',
    'UNCANNY',
    'UNITEDRAKE',
    'UnPacMan',
    'VAGRANT',
    'VALIANTSURF',
    'VALIDATOR',
    'VICTORYDANCE',
    'VIEWPLATE',
    'VINYLSEAT',
    'VIOLETSPIRIT',
    'VITALAIR',
    'VITALAIR2',
    'VOYEUR',
    'VULCANDEATHGRIP',
    'WAGONBED',
    'WAITAUTO',
    'WALKERBLACK',
    'WARNVULCANO',
    'WARRIORPRIDE',
    'WATCHER',
    'WAXTITAN',
    'WEASELWAGGLE',
    'WELLSPRING',
    'WIDOWKEY',
    'WHISTLINGDUXIE',
    'WHITESPYDER',
    'WICKEDVICAR',
    'WIDOWKEY',
    'WILDCHOCOBO',
    'WILDCOUGAR',
    'WILLOWVIXEN',
    'WISTFULTOLL',
    'WINTERLIGHT',
    'WOBBLYLLAMA',
    'XTRACTPLEASING',
    'YELLOWPIN',
    'YELLOWSPIRIT',
    'YELLPIG',
    'ZEBEDEE',
    'ZESTYLEAK',
    'ZEUS',
    'ZORIPIG'
);

/*
 * Generate an RSS feed with 25 randomly chosen elements
 */
$headlines = array();

for ($i = 0; $i < 25; $i++) {
    
    //Select a random keyword
    $keyword = $keywords[rand(0, count($keywords)-1)];
    
    //Potentially fudge with capitalization
    switch (rand(0, 9)) {
        case 0:
            $keyword = strtolower($keyword);
            break;
        case 1:
            $keyword = strtoupper($keyword);
            break;
        case 2:
            $keyword = ucfirst(strtolower($keyword));
            break;
        case 3:
            $keyword = ucwords(strtolower($keyword));
            break;
        default:
            break;
    }
    
    $headlines[] = $keyword;
}

$date = gmdate('D, d M Y H:i:s') . ' GMT';
header('Content-Type: text/xml; charset=utf-8');

echo <<<EOT
<rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>XKEYSCORE Top Stories</title>
    <language>en-US</language>
    <lastBuildDate>{$date}</lastBuildDate>
EOT;

foreach ($headlines as $random) {
  echo <<<EOT

    <item>
      <title>{$random}</title>
      <pubDate>{$date}</pubDate>
      <description>{$random}</description>
    </item>
EOT;
}

echo <<<EOT

  </channel>
</rss>
EOT;
